=begin
#Sync for Commerce

#The API for Sync for Commerce.   Sync for Commerce automatically replicates and reconciles sales data from a merchant’s source PoS, Payments, and eCommerce systems into their accounting software. This eliminates manual processing by merchants and transforms their ability to run and grow their business.    [Read More...](https://docs.codat.io/commerce/overview)  Not seeing the endpoints you're expecting? We've [reorganized our products](https://docs.codat.io/updates/230901-new-products), and you may be using a [different version of Sync for Commerce](https://docs.codat.io/sync-for-commerce-v1-api#/).

The version of the OpenAPI document: 1.1
Contact: syncforcommerce@codat.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  class FeatureState
    RELEASE = "Release".freeze
    ALPHA = "Alpha".freeze
    BETA = "Beta".freeze
    DEPRECATED = "Deprecated".freeze
    NOT_SUPPORTED = "NotSupported".freeze
    NOT_IMPLEMENTED = "NotImplemented".freeze

    def self.all_vars
      @all_vars ||= [RELEASE, ALPHA, BETA, DEPRECATED, NOT_SUPPORTED, NOT_IMPLEMENTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if FeatureState.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #FeatureState"
    end
  end
end
