=begin
#Platform API

#An API for the common components of all of Codat's products.  These end points cover creating and managing your companies, data connections, and integrations.  [Read about the building blocks of Codat...](https://docs.codat.io/core-concepts/companies)  [See our OpenAPI spec](https://github.com/codatio/oas) 

The version of the OpenAPI document: 3.0.0
Contact: support@codat.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  class PushChangeType
    UNKNOWN = "Unknown".freeze
    CREATED = "Created".freeze
    MODIFIED = "Modified".freeze
    DELETED = "Deleted".freeze
    ATTACHMENT_UPLOADED = "AttachmentUploaded".freeze

    def self.all_vars
      @all_vars ||= [UNKNOWN, CREATED, MODIFIED, DELETED, ATTACHMENT_UPLOADED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PushChangeType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PushChangeType"
    end
  end
end
