=begin
#Sync for Commerce

#The API for Sync for Commerce.   Sync for Commerce automatically replicates and reconciles sales data from a merchant’s source PoS, Payments, and eCommerce systems into their accounting software. This eliminates manual processing by merchants and transforms their ability to run and grow their business.    [Read More...](https://docs.codat.io/commerce/overview)  Not seeing the endpoints you're expecting? We've [reorganized our products](https://docs.codat.io/updates/230901-new-products), and you may be using a [different version of Sync for Commerce](https://docs.codat.io/sync-for-commerce-v1-api#/).

The version of the OpenAPI document: 1.1
Contact: syncforcommerce@codat.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AdvancedControlsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AdvancedControlsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AdvancedControlsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdvancedControlsApi' do
    it 'should create an instance of AdvancedControlsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AdvancedControlsApi)
    end
  end

  # unit tests for create_company
  # Create company
  # Creates a Codat company
  # @param [Hash] opts the optional parameters
  # @option opts [CreateCompany] :create_company 
  # @return [Company]
  describe 'create_company test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_configuration
  # Get company configuration
  # Returns a company&#39;s commerce sync configuration&#39;.
  # @param company_id Unique identifier for a company.
  # @param [Hash] opts the optional parameters
  # @return [Configuration]
  describe 'get_configuration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_companies
  # List companies
  # Returns a list of companies.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number. [Read more](https://docs.codat.io/using-the-api/paging).
  # @option opts [Integer] :page_size Number of records to return in a page. [Read more](https://docs.codat.io/using-the-api/paging).
  # @option opts [String] :query Codat query string. [Read more](https://docs.codat.io/using-the-api/querying).
  # @option opts [String] :order_by Field to order results by. [Read more](https://docs.codat.io/using-the-api/ordering-results).
  # @return [Companies]
  describe 'list_companies test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_configuration
  # Set configuration
  # Sets a company&#39;s commerce sync configuration.
  # @param company_id Unique identifier for a company.
  # @param [Hash] opts the optional parameters
  # @return [Configuration]
  describe 'set_configuration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
