=begin
#Platform API

#An API for the common components of all of Codat's products.  These end points cover creating and managing your companies, data connections, and integrations.  [Read about the building blocks of Codat...](https://docs.codat.io/core-concepts/companies)  [See our OpenAPI spec](https://github.com/codatio/oas) 

The version of the OpenAPI document: 3.0.0
Contact: support@codat.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SupplementalDataApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SupplementalDataApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SupplementalDataApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SupplementalDataApi' do
    it 'should create an instance of SupplementalDataApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SupplementalDataApi)
    end
  end

  # unit tests for configure_supplemental_data
  # Configure
  # The *Configure* endpoint allows you to maintain or change configuration required to return supplemental data for each integration and data type combination.  [Supplemental data](https://docs.codat.io/using-the-api/additional-data) is additional data you can include in Codat&#39;s standard data types.  **Integration-specific behaviour** See the *examples* for integration-specific frequently requested properties.
  # @param platform_key A unique 4-letter key to represent a platform in each integration. View [accounting](https://docs.codat.io/integrations/accounting/overview#platform-keys), [banking](https://docs.codat.io/integrations/banking/overview#platform-keys), and [commerce](https://docs.codat.io/integrations/commerce/overview#platform-keys) platform keys.
  # @param data_type Supported supplemental data data type.
  # @param [Hash] opts the optional parameters
  # @option opts [SupplementalDataConfiguration] :supplemental_data_configuration The configuration for the specified platform and data type.
  # @return [nil]
  describe 'configure_supplemental_data test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_supplemental_data_configuration
  # Get configuration
  # The *Get configuration* endpoint returns supplemental data configuration previously created for each integration and data type combination.  [Supplemental data](https://docs.codat.io/using-the-api/additional-data) is additional data you can include in Codat&#39;s standard data types.
  # @param platform_key A unique 4-letter key to represent a platform in each integration. View [accounting](https://docs.codat.io/integrations/accounting/overview#platform-keys), [banking](https://docs.codat.io/integrations/banking/overview#platform-keys), and [commerce](https://docs.codat.io/integrations/commerce/overview#platform-keys) platform keys.
  # @param data_type Supported supplemental data data type.
  # @param [Hash] opts the optional parameters
  # @return [SupplementalDataConfiguration]
  describe 'get_supplemental_data_configuration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
