=begin
#Platform API

#An API for the common components of all of Codat's products.  These end points cover creating and managing your companies, data connections, and integrations.  [Read about the building blocks of Codat...](https://docs.codat.io/core-concepts/companies)  [See our OpenAPI spec](https://github.com/codatio/oas) 

The version of the OpenAPI document: 3.0.0
Contact: support@codat.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PushOptionType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PushOptionType do
  let(:instance) { OpenapiClient::PushOptionType.new }

  describe 'test an instance of PushOptionType' do
    it 'should create an instance of PushOptionType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PushOptionType)
    end
  end

end
