=begin
#Sync for Commerce

#The API for Sync for Commerce.   Sync for Commerce automatically replicates and reconciles sales data from a merchant’s source PoS, Payments, and eCommerce systems into their accounting software. This eliminates manual processing by merchants and transforms their ability to run and grow their business.    [Read More...](https://docs.codat.io/commerce/overview)  Not seeing the endpoints you're expecting? We've [reorganized our products](https://docs.codat.io/updates/230901-new-products), and you may be using a [different version of Sync for Commerce](https://docs.codat.io/sync-for-commerce-v1-api#/).

The version of the OpenAPI document: 1.1
Contact: syncforcommerce@codat.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/branding'
require 'openapi_client/models/branding_button'
require 'openapi_client/models/branding_image'
require 'openapi_client/models/branding_logo'
require 'openapi_client/models/company'
require 'openapi_client/models/company_sync_status'
require 'openapi_client/models/configuration'
require 'openapi_client/models/connection'
require 'openapi_client/models/create_connection_request'
require 'openapi_client/models/data_connection_error'
require 'openapi_client/models/data_connection_status'
require 'openapi_client/models/data_type_feature'
require 'openapi_client/models/error_validation'
require 'openapi_client/models/error_validation_item'
require 'openapi_client/models/feature_state'
require 'openapi_client/models/group_reference'
require 'openapi_client/models/hal_ref'
require 'openapi_client/models/image_reference'
require 'openapi_client/models/integration'
require 'openapi_client/models/items'
require 'openapi_client/models/links'
require 'openapi_client/models/source_type'
require 'openapi_client/models/sync_flow_url'
require 'openapi_client/models/sync_range_date_range'
require 'openapi_client/models/sync_status'
require 'openapi_client/models/sync_summary'
require 'openapi_client/models/sync_summary_sync_date_range_utc'
require 'openapi_client/models/visible_accounts'

# APIs
require 'openapi_client/api/advanced_controls_api'
require 'openapi_client/api/connections_api'
require 'openapi_client/api/integrations_api'
require 'openapi_client/api/sync_api'
require 'openapi_client/api/sync_flow_settings_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
